export type WeddingLocation = { city: string; country: string };

export const WEDDING_LOCATIONS: WeddingLocation[] = [
  // Europe
  { city: "Paris", country: "France" },
  { city: "Santorini", country: "Greece" },
  { city: "Tuscany", country: "Italy" },
  { city: "Amalfi Coast", country: "Italy" },
  { city: "Lake Como", country: "Italy" },
  { city: "Rome", country: "Italy" },
  { city: "Venice", country: "Italy" },
  { city: "Florence", country: "Italy" },
  { city: "Barcelona", country: "Spain" },
  { city: "Mallorca", country: "Spain" },
  { city: "Ibiza", country: "Spain" },
  { city: "Marbella", country: "Spain" },
  { city: "Dubrovnik", country: "Croatia" },
  { city: "Hvar", country: "Croatia" },
  { city: "Split", country: "Croatia" },
  { city: "Lisbon", country: "Portugal" },
  { city: "Algarve", country: "Portugal" },
  { city: "Sintra", country: "Portugal" },
  { city: "London", country: "United Kingdom" },
  { city: "Edinburgh", country: "United Kingdom" },
  { city: "Cotswolds", country: "United Kingdom" },
  { city: "Lake District", country: "United Kingdom" },
  { city: "Vienna", country: "Austria" },
  { city: "Salzburg", country: "Austria" },
  { city: "Prague", country: "Czech Republic" },
  { city: "Amsterdam", country: "Netherlands" },
  { city: "Bruges", country: "Belgium" },
  { city: "Zurich", country: "Switzerland" },
  { city: "Lucerne", country: "Switzerland" },
  { city: "Interlaken", country: "Switzerland" },
  { city: "Lake Bled", country: "Slovenia" },
  { city: "Ljubljana", country: "Slovenia" },
  { city: "Portorož", country: "Slovenia" },
  { city: "Bohinj", country: "Slovenia" },
  { city: "Mykonos", country: "Greece" },
  { city: "Crete", country: "Greece" },
  { city: "Athens", country: "Greece" },
  { city: "Budapest", country: "Hungary" },
  { city: "Stockholm", country: "Sweden" },
  { city: "Copenhagen", country: "Denmark" },
  { city: "Berlin", country: "Germany" },
  { city: "Munich", country: "Germany" },
  { city: "Nice", country: "France" },
  { city: "Provence", country: "France" },
  { city: "Bordeaux", country: "France" },
  { city: "Château de Versailles", country: "France" },
  // Caribbean & Americas
  { city: "Punta Cana", country: "Dominican Republic" },
  { city: "Cancún", country: "Mexico" },
  { city: "Tulum", country: "Mexico" },
  { city: "Los Cabos", country: "Mexico" },
  { city: "Jamaica", country: "Jamaica" },
  { city: "Barbados", country: "Barbados" },
  { city: "Aruba", country: "Aruba" },
  { city: "St. Lucia", country: "Saint Lucia" },
  { city: "Bahamas", country: "Bahamas" },
  { city: "Puerto Rico", country: "Puerto Rico" },
  { city: "Turks and Caicos", country: "Turks and Caicos" },
  // USA
  { city: "New York", country: "United States" },
  { city: "Los Angeles", country: "United States" },
  { city: "Las Vegas", country: "United States" },
  { city: "Miami", country: "United States" },
  { city: "Hawaii", country: "United States" },
  { city: "Napa Valley", country: "United States" },
  { city: "Savannah", country: "United States" },
  { city: "Charleston", country: "United States" },
  { city: "Nashville", country: "United States" },
  { city: "San Francisco", country: "United States" },
  { city: "Austin", country: "United States" },
  // Asia & Pacific
  { city: "Bali", country: "Indonesia" },
  { city: "Phuket", country: "Thailand" },
  { city: "Koh Samui", country: "Thailand" },
  { city: "Tokyo", country: "Japan" },
  { city: "Kyoto", country: "Japan" },
  { city: "Singapore", country: "Singapore" },
  { city: "Maldives", country: "Maldives" },
  { city: "Sri Lanka", country: "Sri Lanka" },
  { city: "Goa", country: "India" },
  { city: "Udaipur", country: "India" },
  { city: "Fiji", country: "Fiji" },
  { city: "Queenstown", country: "New Zealand" },
  { city: "Sydney", country: "Australia" },
  { city: "Melbourne", country: "Australia" },
  { city: "Byron Bay", country: "Australia" },
  // Middle East & Africa
  { city: "Dubai", country: "United Arab Emirates" },
  { city: "Marrakech", country: "Morocco" },
  { city: "Cape Town", country: "South Africa" },
  { city: "Seychelles", country: "Seychelles" },
  { city: "Mauritius", country: "Mauritius" },
  { city: "Zanzibar", country: "Tanzania" },
];

export function searchLocations(query: string, limit = 8): WeddingLocation[] {
  const q = query.toLowerCase().trim();
  if (q.length < 2) return [];
  return WEDDING_LOCATIONS.filter(
    (l) => l.city.toLowerCase().includes(q) || l.country.toLowerCase().includes(q),
  ).slice(0, limit);
}
